---
- name: Combinaison des dictionnaires odoo
  set_fact:
    in_nginx_dict: "{{ in_nginx_dict|default({})|combine({item.key : item.value}, recursive=True) }}"
  with_dict: "{{ nginx_dict }}"
  when: nginx_dict is defined

- name: "Install nginx"
  become: yes
  yum:
    name: "nginx"
    state: present

- name: Debug var
  debug:
    var: in_nginx_dict

- name: Create directory for configuration files
  become: yes
  file:
     state: directory
     path: "{{ item }}"
     owner: "{{ in_nginx_dict['user'] }}"
     group: "{{ in_nginx_dict['group'] }}"
     mode: "0755"
  with_items:
    - "{{ in_nginx_dict['basedir'] }}/sites-enabled"
    - "{{ in_nginx_dict['basedir'] }}/sites-available"

# SELINUX :
#ausearch -m avc -ts today | audit2allow
# POUR voir ce QUI POSE PROBLEME :
#sudo cat /var/log/audit/audit.log | grep nginx | grep denied | audit2allow -w -a
#  308  cat /var/log/audit/audit.log | grep nginx | grep denied | audit2allow -M mynginx
#  311  sudo -i semodule -i mynginx.pp
- name: Permission SELinux
  become: yes
  selinux_permissive:
    name: httpd_t
    permissive: true

- name: "Enable service nginx"
  become: yes
  systemd:
    name: nginx
    state: started
    enabled: yes

